# Generated by Django 5.0.3 on 2024-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portflyCrab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usracceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('seed', models.CharField(max_length=40)),
            ],
        ),
    ]
