# Generated by Django 5.0.3 on 2024-05-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portflyCrab', '0002_usracceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
